import {
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarDays,
  CircleHelp,
  CreditCard,
  GraduationCap,
  Home,
  LayoutDashboard,
  LogOut,
  Menu,
  Mountain,
  Plus,
  Radio,
  Search,
  Star,
  TrendingUp,
  User,
  Users,
  Video,
  Wallet,
  X,
  CheckCircle2,
  CircleDollarSign
} from "lucide-react";

/** @type {Record<string, import('lucide-react').LucideIcon>} */
export const iconMap = {
  dashboard: LayoutDashboard,
  home: Home,
  users: Users,
  video: Video,
  creditCard: CreditCard,
  barChart: BarChart3,
  calendar: Calendar,
  calendarDays: CalendarDays,
  plus: Plus,
  wallet: Wallet,
  user: User,
  book: BookOpen,
  school: Building2,
  help: CircleHelp,
  bell: Bell,
  logout: LogOut,
  menu: Menu,
  close: X,
  mountain: Mountain,
  check: CheckCircle2,
  star: Star,
  graduation: GraduationCap,
  trending: TrendingUp,
  bank: Building2,
  live: Radio,
  money: CircleDollarSign,
  search: Search,
  arrowRight: ArrowRight
};

export function resolveIcon(name) {
  return iconMap[name] || Home;
}
