import {
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarDays,
  CircleHelp,
  CreditCard,
  GraduationCap,
  Home,
  LayoutDashboard,
  LogOut,
  Menu,
  Mountain,
  Plus,
  Radio,
  Search,
  Shield,
  Star,
  TrendingUp,
  User,
  Users,
  Video,
  Wallet,
  X,
  CheckCircle2,
  CircleDollarSign,
  ChevronDown,
  Gift,
  Globe,
  PenLine,
  Tag,
  RefreshCw,
  Lock,
  Unlock,
  Download,
  FileText,
  Eye
} from "lucide-react";

/** @type {Record<string, import('lucide-react').LucideIcon>} */
export const iconMap = {
  dashboard: LayoutDashboard,
  home: Home,
  users: Users,
  video: Video,
  creditCard: CreditCard,
  barChart: BarChart3,
  calendar: Calendar,
  calendarDays: CalendarDays,
  plus: Plus,
  wallet: Wallet,
  user: User,
  book: BookOpen,
  school: Building2,
  help: CircleHelp,
  bell: Bell,
  logout: LogOut,
  menu: Menu,
  close: X,
  mountain: Mountain,
  check: CheckCircle2,
  star: Star,
  graduation: GraduationCap,
  trending: TrendingUp,
  bank: Building2,
  live: Radio,
  money: CircleDollarSign,
  search: Search,
  shield: Shield,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  gift: Gift,
  edit: PenLine,
  tag: Tag,
  globe: Globe,
  refresh: RefreshCw,
  lock: Lock,
  unlock: Unlock,
  download: Download,
  description: FileText,
  visibility: Eye
};

export function resolveIcon(name) {
  return iconMap[name] || Home;
}
